### PR TITLE
Fix multiarch support on Debian/Ubuntu

### PR DESCRIPTION
**Pull request by noirbizarre**
Allow installation from pip/easy_install on multiarch enabled distrib.

See https://wiki.ubuntu.com/MultiarchSpec

I think there some fix to apply to mapnik-utils too.

Backporting to 2.0.x to have it in pypi would be very nice!

### CODE REVIEW

**Comment by kiorky** [comment]
Thx !

**Comment by kiorky** [comment]
http://pypi.python.org/pypi/mapnik2/2.0.2#id3 :)

**Comment by kiorky** [comment]
I can also make you co maintainer of pypi, just give me your id.
Just use zest.releaser's fullrelease (see buildout) to make a proper release.

**Comment by noirbizarre** [comment]
Glad to help!!
Here's my pypi ID: noirbizarre (same as github)

I don't much about zest-releaser but it seems interesting.
I going learn about it right now!

Thanks!

**Comment by kiorky** [comment]
added to pypi as maintainer 

basically:
- have the buildout running 
- easy_install -U setuptools_git (you need it both in your buildout scripts & in your python because zest.releaser calls directly python under the hood)
- then when you release, commits what it needs to, but dont increment any version stuff nor update the date in CHANGES because it is handled by zest.releaser
- finally use the magical bin/fullrelease, answer the questions are you are done.
  - tag creation, version increment, date update, pypi & github checkins will be handled for you

**Pull request merged**
